language: cpp
compiler: 
  - clang
  - gcc
os:
  - linux

sudo: required
addons:
  apt:
    sources:  
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7
      - g++-5
      - gcc-5

before_script:
  - if [ ${CXX} = 'clang++' ]; then export CXX='clang++-3.7'; fi
  - if [ ${CXX} = 'g++' ]; then export CXX='g++-5'; fi
script:
  - mkdir build
  - cd build
  - cmake .. && make

notifications:
  email: false
